prev: Antigos
next: Novos
comment: Comentários
archive_a: Arquivos
archive_b: "Arquivos: %s"
about: Sobre
recent_posts: "Atualizações Recentes"
categories: "Categorias"
default_post_title: "Untitled"
category: Categorias
tag: Tag